In [1]:
import numpy as np

In [2]:
X=np.array([[240,22,153,100],[35,213,45,120],[100,45,67,25]])
print('images\n',X)
W=np.array([[.2,.5,.9],[.1,.5,.8],[.3,.7,.4],[.6,.9,.1]])
print('weights\n',W)
y=(1,0,2)
print('labels\n',y)

images
 [[240  22 153 100]
 [ 35 213  45 120]
 [100  45  67  25]]
weights
 [[0.2 0.5 0.9]
 [0.1 0.5 0.8]
 [0.3 0.7 0.4]
 [0.6 0.9 0.1]]
labels
 (1, 0, 2)


# Softmax naive

In [22]:
dW=np.zeros(W.shape)
num_train = X.shape[0]
print('num of training images\n',num_train)
num_classes = W.shape[1]
print('num of classes\n',num_classes)
loss = 0.0
for i in range(num_train):
    print('i=',i)
    scores = X[i].dot(W)
    print('scores\n',scores)
    scores -= np.max(scores)
    print('Scores\n',scores)
    correct_class_score= scores[y[i]]
    print('correct_class_score\n',correct_class_score)
   
    sum_j = np.sum(np.exp(scores))
    print('sum_j\n',sum_j)
    softmax =np.exp(correct_class_score) / sum_j
    print('softmax\n',softmax)
    loss += -np.log(softmax)
    print('loss\n',loss)
    
    for j in range(num_classes):
        print('j == y[',i,']')
        if j == y[i]:
            print('scores[j]\n',scores[j])
            
            dW[:, y[i]] += ((np.exp(scores[j]) / sum_j) - 1) * X[i, :]
            print('dW after X[',i,']=',X[i],' is multiplied with softmax correct class ',j,' coordinate\n',dW)
        else:
            print('scores[j]\n',scores[j])
            dW[:, j] += ((np.exp(scores[j]))/ sum_j) * X[i, :]
            print('dW after X[',i,']=',X[i],' is multiplied with softmax other class',j,' coordinate\n',dW)
    
loss /= num_train
#print('loss\n',loss)
dW /= num_train
#print('dW \n',dW )



num of training images
 3
num of classes
 3
i= 0
scores
 [156.1 328.1 304.8]
Scores
 [-172.     0.   -23.3]
correct_class_score
 0.0
sum_j
 1.0000000000760219
softmax
 0.9999999999239781
loss
 7.602185548028248e-11
j == y[ 0 ]
scores[j]
 -172.00000000000003
dW after X[ 0 ]= [240  22 153 100]  is multiplied with softmax other class 0  coordinate
 [[4.80352831e-73 0.00000000e+00 0.00000000e+00]
 [4.40323428e-74 0.00000000e+00 0.00000000e+00]
 [3.06224930e-73 0.00000000e+00 0.00000000e+00]
 [2.00147013e-73 0.00000000e+00 0.00000000e+00]]
j == y[ 0 ]
scores[j]
 0.0
dW after X[ 0 ]= [240  22 153 100]  is multiplied with softmax correct class  1  coordinate
 [[ 4.80352831e-73 -1.82452453e-08  0.00000000e+00]
 [ 4.40323428e-74 -1.67248082e-09  0.00000000e+00]
 [ 3.06224930e-73 -1.16313439e-08  0.00000000e+00]
 [ 2.00147013e-73 -7.60218555e-09  0.00000000e+00]]
j == y[ 0 ]
scores[j]
 -23.30000000000001
dW after X[ 0 ]= [240  22 153 100]  is multiplied with softmax other class 2  coordinate
 [[

# Softmax vectorized

In [17]:
loss = 0.0
dW = np.zeros_like(W)
print('dW\n',dW)
   
num_train = X.shape[0]
scores = X.dot(W)
print('scores\n',scores)
print('dimscores\n',scores.shape)
scores = scores - np.max(scores, axis=1)[:,np.newaxis]

print('scores\n',scores)
print('dimscores\n',scores.shape)
softmax= (np.exp(scores))/ np.sum(np.exp(scores), axis=1)
print('softmax\n',softmax)

loss += -np.sum(np.log(softmax[np.arange(num_train), y])) 
print('loss\n',loss)
loss /= num_train

intg = np.zeros_like(scores)
print('intg\n',intg)
intg[np.arange(num_train), y] = 1
print('intg\n',intg)
dW = X.T.dot(softmax-intg)
print('dW\n',dW)

loss /= num_train
#print('loss\n',loss)
dW /= num_train
#print('dW \n',dW )

dW
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
scores
 [[156.1 328.1 304.8]
 [113.8 263.5 231.9]
 [ 59.6 141.9 155.3]]
dimscores
 (3, 3)
scores
 [[-172.     0.   -23.3]
 [-149.7    0.   -31.6]
 [ -95.7  -13.4    0. ]]
dimscores
 (3, 3)
softmax
 [[2.00147013e-75 1.00000000e+00 7.60217589e-11]
 [9.68536649e-66 1.00000000e+00 1.88926863e-14]
 [2.74168832e-42 1.51514411e-06 9.99998485e-01]]
loss
 149.70000151521901
intg
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
intg
 [[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]
dW
 [[-3.50000000e+01  3.50001515e+01 -1.51495936e-04]
 [-2.13000000e+02  2.13000068e+02 -6.81797052e-05]
 [-4.50000000e+01  4.50001015e+01 -1.01502870e-04]
 [-1.20000000e+02  1.20000038e+02 -3.78709410e-05]]
